from mutable_lattice import Vector
from . import ProjectiveResolution

def _minimial_ideal_structure(op):
    """Return subsets of the minimal ideal of a semigroup defining its structure"""
    rn = range(len(op))
    # The product of all elements is in the minimal ideal
    k = 0
    for x in rn:
        k = op[k][x]
    k = op[k][0] # try to prefer element 0
    # The minimal left and right ideals containing k
    kS = {op[k][x] for x in rn}
    Sk = {op[x][k] for x in rn}
    # The maximal subgroup containing k
    H = kS & Sk
    I = {i for i in Sk if op[i][i] == i}
    J = {j for j in kS if op[j][j] == j}
    return H, I, J

def _normal_subgroup_generated(H, op, subset):
    """
    Given a group H as a subgroup of the semigroup defined by op,
    along with some subset of H, find the normal subgroup of H generated by that subset.
    """
    [e] = [e for e in H if op[e][e] == e]
    h_inverses = {h: hinv for h in H for hinv in H if op[h][hinv] == e}
    conjugates = {op[h][op[q][hinv]]
                  for q in set(subset)
                  for h, hinv in h_inverses.items()}
    N = set()
    active = [e]
    while active:
        h = active.pop()
        if h not in N:
            N.add(h)
            for conj in conjugates:
                active.append(op[h][conj])
    return N

def _quotient_group(H, op, subset):
    N = _normal_subgroup_generated(H, op, subset)
    H_remaining = set(H)
    representatives = []
    H_to_G_index = {}
    for h in sorted(H):
        if h in H_remaining:
            i = len(representatives)
            representatives.append(h)
            for n in N:
                hn = op[h][n]
                H_remaining.remove(hn)
                H_to_G_index[hn] = i
    Gop = [[H_to_G_index[op[gi][gj]] for gj in representatives]
           for gi in representatives]
    return Gop, H_to_G_index, representatives

def group_completion(op):
    """
    Calculate the maximal homomorphic group image G of a semigroup or monoid S.

    Return a 3-tuple of:
        * Gop : list[list[int]] -- the multiplication table of G,
        * mapping : list[int] -- the image in G of each element of S.
        * representatives : list[int] -- one preimage in S of each element of G.
    """
    # See https://arxiv.org/abs/2502.05276v2, Lemma 2.1:
    #   The group completion is the quotient of any maximal subgroup of the minimal
    #   ideal by the normal subgroup generated by all sandwich matrices entries.
    H, I, J = _minimial_ideal_structure(op)
    [e] = [e for e in H if op[e][e] == e]
    JI = {op[j][i] for i in I for j in J}
    Gop, H_to_G_index, representatives = _quotient_group(H, op, JI)
    mapping = [H_to_G_index[op[e][op_x[e]]] for op_x in op]
    return Gop, mapping, representatives

def group_completion_functor_map(op1, op2, f):
    """
    Given multiplication tables op1 and op2 for semigroups or monoids
    and a morphism f : list[int] between them,
    produce a triple (Gop1, Gop2, Gfunc),
    where Gop1 and Gop2 are the group completion multiplication tables
    and Gfunc is the map between them induced by f.
    """
    Gop1, mapping1, representatives1 = group_completion(op1)
    Gop2, mapping2, representatives2 = group_completion(op2)
    Gfunc = [mapping2[f[rep_g]] for rep_g in representatives1]
    return Gop1, Gop2, Gfunc

def map_induces_isomorphism_on_group_completion(op1, op2, f):
    """Determine whether Bf : B(op1) --> B(op2) induces an isomorphism on pi1"""
    Gop1, Gop2, Gfunc = group_completion_functor_map(op1, op2, f)
    return len(Gop1) == len(Gop2) and len(set(Gfunc)) == len(Gop2)

def universal_cover_resolution(op):
    """Tor^ZS_i(Z, ZG(S)) computes the homology of the universal cover of BS, so find a resolution of ZG(S)."""
    Gop, mapping, representatives = group_completion(op)
    action = [Vector(Gop[mapping_x]) for mapping_x in mapping]
    return ProjectiveResolution(op, left_S_set_action=action)

def universal_cover_homology_list(op, maxdim):
    """The homology of the universal cover of the classifying space of a monoid"""
    res = universal_cover_resolution(op)
    return res.homology_list(maxdim)

def pi2(op):
    """The second homotopy group of the classifying space of a monoid"""
    return universal_cover_homology_list(op, 2)[2]

